name: Remote Unity Repo Build

on:
  workflow_dispatch:
    inputs:
      unity_repo_url:
        description: 'GitHub link of the Unity project to build'
        required: true
        default: 'https://github.com/YourOrg/YourUnityRepo.git'

jobs:
  build-xcode:
    runs-on: macos-latest

    steps:
    - name: Checkout this workflow repo (for BuildHelper.cs, etc)
      uses: actions/checkout@v4

    - name: Clone Unity project repo (with org-wide PAT)
      run: |
        repo_url="${{ github.event.inputs.unity_repo_url }}"
        repo_url_auth=$(echo "$repo_url" | sed "s#https://github.com/#https://x-access-token:${{ secrets.ORG_WIDE_PAT }}@github.com/#")
        git clone "$repo_url_auth" UnityProject

    - name: Display Unity project files
      run: ls -la UnityProject

    - name: Inject BuildHelper.cs for CI build
      run: |
        mkdir -p "UnityProject/Assets/Editor"
        cp ".github/helpers/BuildHelper.cs" "UnityProject/Assets/Editor/BuildHelper.cs"

    - name: Build Unity project to Xcode with game-ci/unity-builder
      uses: game-ci/unity-builder@v4
      with:
        projectPath: UnityProject
        targetPlatform: iOS
        buildMethod: BuildHelper.PerformBuild
        versioning: None

    - name: List output
      run: ls -la UnityProject
