name: Build Unity to Xcode

on:
  workflow_dispatch:

jobs:
  build-xcode:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Display files
      run: ls -la

    - name: Extract Unity version from project
      id: unity-version
      run: |
        UNITY_VERSION=$(grep 'm_EditorVersion:' ProjectSettings/ProjectVersion.txt | awk '{print $2}')
        echo "UNITY_VERSION=$UNITY_VERSION" >> $GITHUB_ENV

    - name: Install Unity
      uses: game-ci/unity-installer@v3
      with:
        version: ${{ env.UNITY_VERSION }}
        ios: true

    - name: Inject BuildHelper.cs for CI build
      run: |
        mkdir -p "Assets/Editor"
        cp "ci/BuildHelper.cs" "Assets/Editor/BuildHelper.cs"

    - name: Build Unity project to Xcode
      run: |
        UNITY_PATH="/Applications/Unity/Hub/Editor/${UNITY_VERSION}/Unity.app/Contents/MacOS/Unity"
        PROJECT_PATH="$GITHUB_WORKSPACE"
        if [ ! -x "$UNITY_PATH" ]; then
          echo "❌ Unity not found at $UNITY_PATH"
          exit 1
        fi
        "$UNITY_PATH" -batchmode -quit -projectPath "$PROJECT_PATH" \
          -buildTarget iOS \
          -executeMethod BuildHelper.PerformBuild

    - name: List output
      run: ls -la "$GITHUB_WORKSPACE"
